export function createSeedState() {
  const now = new Date().toISOString();

  return {
    meta: {
      version: 1,
      createdAt: now,
      updatedAt: now,
    },
    editais: [],
    artistas: [],
    projetos: [],
    documentos: [],
    oportunidades: [],
    sources: [
      {
        id: "source_1",
        name: "MinC - Editais",
        type: "html",
        url: "https://www.gov.br/cultura/pt-br/assuntos/editais",
        active: true,
        frequencyMinutes: 360,
        notes: "Página principal de editais do Ministério da Cultura.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_2",
        name: "MinC - Cultura Viva",
        type: "html",
        url: "https://www.gov.br/culturaviva/pt-br/acesso-a-informacao/editais/editais-diversos-ministerio-da-cultura",
        active: true,
        frequencyMinutes: 720,
        notes: "Editais e chamadas da rede Cultura Viva.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_3",
        name: "MinC - Modelos PNAB",
        type: "html",
        url: "https://www.gov.br/cultura/pt-br/assuntos/politica-nacional-aldir-blanc/modelos-de-editais",
        active: true,
        frequencyMinutes: 1440,
        notes: "Modelos e referências da Política Nacional Aldir Blanc.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_4",
        name: "MinC - Audiovisual",
        type: "html",
        url: "https://www.gov.br/cultura/pt-br/assuntos/cinema-do-brasil/fomento-1/editais",
        active: true,
        frequencyMinutes: 720,
        notes: "Editais e chamadas da Secretaria do Audiovisual.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_5",
        name: "MinC - Editais Encerrados",
        type: "html",
        url: "https://www.gov.br/cultura/pt-br/assuntos/editais/inscricoes-encerradas/editais-encerrados/",
        active: true,
        frequencyMinutes: 1440,
        notes: "Referência histórica de chamadas encerradas e estrutura editorial.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_6",
        name: "Funarte - Editais",
        type: "html",
        url: "https://www.gov.br/funarte/pt-br/editais-1",
        active: true,
        frequencyMinutes: 720,
        notes: "Portal de editais da Funarte.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_7",
        name: "Funarte - Notícias",
        type: "html",
        url: "https://www.gov.br/funarte/pt-br/assuntos/noticias/todas-noticias",
        active: true,
        frequencyMinutes: 720,
        notes: "Notícias institucionais com chamadas e editais recentes.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_8",
        name: "Palmares - Editais Culturais",
        type: "html",
        url: "https://www.gov.br/palmares/pt-br/acesso-a-informacao/editais-culturais/",
        active: true,
        frequencyMinutes: 720,
        notes: "Editais culturais da Fundação Cultural Palmares.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_9",
        name: "Ancine - Notícias",
        type: "html",
        url: "https://www.gov.br/ancine/pt-br/assuntos/noticias",
        active: true,
        frequencyMinutes: 1440,
        notes: "Notícias da Ancine com chamadas e editais do audiovisual.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_10",
        name: "Secult Ceará - Editais",
        type: "html",
        url: "https://www.secult.ce.gov.br/2025/01/09/confira-os-editais-da-politica-nacional-aldir-blanc-de-fomento-que-estao-com-inscricoes-abertas/",
        active: true,
        frequencyMinutes: 1440,
        notes: "Exemplo de editais estaduais em andamento.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_11",
        name: "Goiás Cultura - Editais",
        type: "html",
        url: "https://goias.gov.br/cultura/editais-de-restauro-e-audiovisual-tem-inscricoes-abertas/",
        active: true,
        frequencyMinutes: 1440,
        notes: "Exemplo de fonte estadual com chamadas e editais.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "source_12",
        name: "Prefeitura de Araçatuba - Cultura",
        type: "html",
        url: "https://aracatuba.sp.gov.br/cultura/noticias/inscricoes-para-editais-de-fomento-cultural-de-aracatuba-terminam-nesta-sexta-feira",
        active: true,
        frequencyMinutes: 1440,
        notes: "Fonte municipal com editais culturais.",
        lastSyncAt: null,
        lastError: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    ingestions: [],
    chat: {
      edital: {},
      oportunidade: {},
    },
    auditLog: [],
  };
}
