from __future__ import annotations

from datetime import datetime, timezone


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _source(
    *,
    id: str,
    name: str,
    type: str,
    url: str,
    active: bool,
    frequency_minutes: int,
    notes: str,
    esfera: str,
    confiabilidade: str,
    metodo_captura: str,
    precisa_validacao_humana: bool,
    classificacao: str,
) -> dict:
    now = now_iso()
    return {
        "id": id,
        "name": name,
        "type": type,
        "url": url,
        "active": active,
        "frequencyMinutes": frequency_minutes,
        "notes": notes,
        "esfera": esfera,
        "confiabilidade": confiabilidade,
        "metodoCaptura": metodo_captura,
        "precisaValidacaoHumana": precisa_validacao_humana,
        "classificacao": classificacao,
        "lastSyncAt": None,
        "lastError": None,
        "createdAt": now,
        "updatedAt": now,
    }


def create_seed_state() -> dict:
    return {
        "meta": {
            "version": 2,
            "createdAt": now_iso(),
            "updatedAt": now_iso(),
        },
        "editais": [],
        "artistas": [],
        "projetos": [],
        "documentos": [],
        "oportunidades": [],
        "matches": [],
        "sources": [
            _source(
                id="source_1",
                name="Ministério da Cultura / Gov.br",
                type="html",
                url="https://www.gov.br/cultura/pt-br/assuntos/editais",
                active=True,
                frequency_minutes=360,
                notes="Fonte oficial federal para editais nacionais, PNAB e chamadas públicas.",
                esfera="federal",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="edital",
            ),
            _source(
                id="source_2",
                name="Mapa da Cultura",
                type="html",
                url="https://mapa.cultura.gov.br/",
                active=True,
                frequency_minutes=720,
                notes="Plataforma oficial para inscrições, oportunidades e agentes culturais.",
                esfera="federal",
                confiabilidade="alta",
                metodo_captura="api",
                precisa_validacao_humana=False,
                classificacao="plataforma",
            ),
            _source(
                id="source_3",
                name="Funarte - Editais",
                type="html",
                url="https://www.gov.br/funarte/pt-br/editais-1/editais-abertos",
                active=True,
                frequency_minutes=360,
                notes="Editais federais de artes, circulação, ocupação e bolsas.",
                esfera="federal",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="edital",
            ),
            _source(
                id="source_4",
                name="Cultura Viva",
                type="html",
                url="https://www.gov.br/culturaviva/pt-br/acesso-a-informacao/editais/editais-diversos-ministerio-da-cultura",
                active=True,
                frequency_minutes=720,
                notes="Chamadas de base comunitária, pontos e pontões de cultura.",
                esfera="federal",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="edital",
            ),
            _source(
                id="source_5",
                name="Salic / Lei Rouanet",
                type="html",
                url="https://www.gov.br/cultura/pt-br/assuntos/lei-rouanet/textos/pesquise-projetos-e-dados",
                active=True,
                frequency_minutes=1440,
                notes="Inteligência de captação e pesquisa de projetos aprovados.",
                esfera="federal",
                confiabilidade="alta",
                metodo_captura="api",
                precisa_validacao_humana=False,
                classificacao="inteligencia",
            ),
            _source(
                id="source_6",
                name="Fomento CultSP / ProAC",
                type="html",
                url="https://fomentocultsp.sp.gov.br/",
                active=True,
                frequency_minutes=360,
                notes="Editais estaduais de São Paulo, PNAB SP e Cultura Viva.",
                esfera="estadual",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="edital",
            ),
            _source(
                id="source_7",
                name="Secult MG - Editais PNAB",
                type="html",
                url="https://www.secult.mg.gov.br/editais/editais-pnab/editais-pnab",
                active=True,
                frequency_minutes=720,
                notes="Bolsas, circulação, pesquisa e intercâmbio em Minas Gerais.",
                esfera="estadual",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="edital",
            ),
            _source(
                id="source_8",
                name="Prosas",
                type="html",
                url="https://produtos.prosas.com.br/editais",
                active=True,
                frequency_minutes=720,
                notes="Plataforma agregadora de editais e inscrições; validar realizador original.",
                esfera="nacional",
                confiabilidade="media",
                metodo_captura="scraping",
                precisa_validacao_humana=True,
                classificacao="agregador",
            ),
            _source(
                id="source_9",
                name="Natura Musical",
                type="html",
                url="https://www.natura.com.br/naturamusical",
                active=True,
                frequency_minutes=1440,
                notes="Chamadas de música, circulação, álbuns e projetos autorais.",
                esfera="privada",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="patrocinio",
            ),
            _source(
                id="source_10",
                name="Petrobras Cultural",
                type="html",
                url="https://petrobras.com.br/cultural/selecoes-publicas-culturais",
                active=True,
                frequency_minutes=1440,
                notes="Seleções públicas culturais e patrocínio temático.",
                esfera="privada",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="patrocinio",
            ),
            _source(
                id="source_11",
                name="Sesc / Sesi / Senac",
                type="html",
                url="https://www.sescsp.org.br/",
                active=True,
                frequency_minutes=1440,
                notes="Programação, circulação, ocupação, festivais e chamadas institucionais.",
                esfera="privada",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="programacao",
            ),
            _source(
                id="source_12",
                name="CCBB / Caixa Cultural / Itaú Cultural",
                type="html",
                url="https://www.itaucultural.org.br/",
                active=True,
                frequency_minutes=1440,
                notes="Convocatórias, ocupação, circulação e programações públicas.",
                esfera="privada",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="chamada",
            ),
            _source(
                id="source_13",
                name="Secretarias Municipais / Diários Oficiais",
                type="html",
                url="https://www.in.gov.br/",
                active=True,
                frequency_minutes=720,
                notes="Varredura de editais municipais e validação oficial por diário público.",
                esfera="municipal",
                confiabilidade="alta",
                metodo_captura="scraping",
                precisa_validacao_humana=False,
                classificacao="edital",
            ),
        ],
        "ingestions": [],
        "chat": {
            "edital": {},
            "oportunidade": {},
        },
        "auditLog": [],
    }


def canonical_sources() -> list[dict]:
    return create_seed_state()["sources"]
