const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || (import.meta.env.PROD ? "/_/backend/api/v1" : "/api/v1");

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`, {
    headers: {
      "Content-Type": "application/json",
      ...(init?.headers || {}),
    },
    ...init,
  });

  if (!response.ok) {
    const message = await response.text();
    throw new Error(message || `Request failed: ${response.status}`);
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return response.json() as Promise<T>;
}

export type ApiSummary = {
  editais: number;
  artistas: number;
  projetos: number;
  documentos: number;
  oportunidades: number;
  matches?: number;
  sources?: number;
  ingestions?: number;
  byStatus: Record<string, Record<string, number>>;
};

export type Edital = {
  id: string;
  nome: string;
  fonte: string;
  fonteUrl?: string | null;
  area: string;
  prazo: number;
  valor: number;
  status: string;
  prioridade: string;
  compatibilidade: number;
  matches: { artistas: number; projetos: number };
  resumo: string;
  quemPodeParticipar: string;
  riscos: string[];
  proximaAcao: string;
  descricaoCompleta: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  analysis?: EditalAnalysis;
};

export type EditalAnalysis = {
  editalId: string;
  resumoExecutivo: string;
  requisitos: string[];
  criterios: Array<{ criterio: string; peso: string }>;
  documentosObrigatorios: string[];
  riscos: string[];
  sugestoes: Array<{
    artistaId: string;
    artista: string;
    projetoId: string | null;
    projeto: string | null;
    compatibilidade: number;
    motivo: string;
    pendencias: number;
  }>;
  proximasAcoes: string[];
  updatedAt: string;
};

export type ChatMessage = {
  id: string;
  role: "assistant" | "user";
  content: string;
  createdAt: string;
  metadata?: {
    sections?: Array<{
      title: string;
      bullets: string[];
    }>;
    actions?: Array<{
      label: string;
      prompt: string;
      kind: "analysis" | "checklist" | "opportunity" | "document" | "risk" | "comparison" | "followup";
    }>;
    highlights?: string[];
    confidence?: number;
  };
};

export type Artista = {
  id: string;
  nome: string;
  tipo: string;
  area: string;
  cidade: string;
  projetos: number;
  oportunidadesAtivas: number;
  statusDocumental: string;
  bio: string;
  links: string[];
  contatos: string[];
  tags: string[];
  createdAt: string;
  updatedAt: string;
};

export type Projeto = {
  id: string;
  artistaId: string;
  nome: string;
  descricao: string;
  status: string;
  orcamento: number;
  editaisRelacionados: string[];
  tags: string[];
  createdAt: string;
  updatedAt: string;
};

export type Documento = {
  id: string;
  nome: string;
  status: string;
  responsavel: string;
  arquivo: string | null;
  ownerType: "artist" | "project" | "opportunity";
  ownerId: string;
  tipo: string;
  validade: string | null;
  oportunidadeId?: string | null;
  editalId?: string | null;
  versao?: string;
  textoExtraido?: string;
  resumoIa?: string;
  checklistGerado?: boolean;
  fonteDocumento?: string | null;
  updatedAt: string;
};

export type Oportunidade = {
  id: string;
  nome: string;
  editalId: string;
  edital: string;
  artistaId: string;
  artista: string;
  projectId: string | null;
  projeto: string | null;
  prazo: number;
  responsavel: string;
  status: string;
  progresso: number;
  pendencias: number;
  risco: string;
  tipo?: string;
  area?: string;
  publicoAlvo?: string;
  territorio?: string;
  valorTotal?: number;
  valorPorProjeto?: number;
  prazoInicio?: string | null;
  prazoFinal?: string | null;
  linkEdital?: string | null;
  linkFormulario?: string | null;
  linkAnexos?: string | null;
  fonteOriginal?: string | null;
  fonteDescoberta?: string | null;
  nivelConfiabilidade?: string;
  dataUltimaChecada?: string | null;
  autoGenerated?: boolean;
  origem?: string;
  tituloOrigem?: string;
  documentosFaltantes: string[];
  checklist: Array<{ tarefa: string; concluido: boolean; responsavel: string; prazo: string }>;
  comentarios: Array<{ autor: string; texto: string; createdAt: string }>;
  protocolo: string | null;
  resultado: string | null;
  createdAt: string;
  updatedAt: string;
};

export type MatchOportunidadeProjeto = {
  id: string;
  oportunidadeId: string;
  editalId: string;
  projetoId: string | null;
  artistaId: string | null;
  notaMatch: number;
  motivoMatch: string;
  riscos: string[];
  documentosFaltantes: string[];
  prazoDeAcao: "urgente" | "normal";
  recomendacao: "inscrever" | "avaliar" | "descartar";
  createdAt: string;
  updatedAt: string;
};

export type ArtistaDetailResponse = {
  item: Artista;
  projetos: Projeto[];
  oportunidades: Oportunidade[];
  documentos: Documento[];
};

export type ListResponse<T> = { items: T[] };

export type Source = {
  id: string;
  name: string;
  type: string;
  url: string;
  active: boolean;
  frequencyMinutes: number;
  notes: string;
  esfera?: string;
  confiabilidade?: string;
  metodoCaptura?: string;
  precisaValidacaoHumana?: boolean;
  classificacao?: string;
  lastSyncAt: string | null;
  lastError: string | null;
  createdAt: string;
  updatedAt: string;
};

export type Ingestion = {
  id: string;
  sourceId: string;
  sourceName: string;
  status: "success" | "error";
  discoveredCount: number;
  createdCount: number;
  startedAt: string;
  finishedAt: string;
  error: string | null;
};

export async function getSummary() {
  return request<ApiSummary>("/summary");
}

export async function listEditais() {
  return request<ListResponse<Edital>>("/editais");
}

export async function createEdital(payload: {
  nome: string;
  fonte: string;
  fonteUrl?: string | null;
  area?: string;
  prazo?: number;
  valor?: number;
  status?: string;
  prioridade?: string;
  compatibilidade?: number;
  matches?: { artistas: number; projetos: number };
  resumo?: string;
  quemPodeParticipar?: string;
  riscos?: string[];
  proximaAcao?: string;
  descricaoCompleta?: string;
  tags?: string[];
}) {
  return request<{ item: Edital }>("/editais", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function importEdital(payload: {
  nome?: string;
  fonte?: string;
  fonteUrl?: string | null;
  area?: string;
  prazo?: number;
  valor?: number;
  prioridade?: string;
  resumo?: string;
  quemPodeParticipar?: string;
  content?: string;
  text?: string;
  tags?: string[];
}) {
  return request<{ item: Edital }>("/editais/import", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function getEdital(id: string) {
  return request<{ item: Edital; analysis: EditalAnalysis }>(`/editais/${id}`);
}

export async function analyzeEdital(id: string) {
  return request<{ analysis: EditalAnalysis }>(`/editais/${id}/analyze`, {
    method: "POST",
  });
}

export async function createOportunidade(payload: {
  editalId: string;
  artistaId: string;
  projectId?: string | null;
  nome?: string;
  responsavel?: string;
  status?: string;
  progresso?: number;
  pendencias?: number;
  risco?: string;
  prazo?: number;
  tipo?: string;
  area?: string;
  publicoAlvo?: string;
  territorio?: string;
  valorTotal?: number;
  valorPorProjeto?: number;
  prazoInicio?: string | null;
  prazoFinal?: string | null;
  linkEdital?: string | null;
  linkFormulario?: string | null;
  linkAnexos?: string | null;
  fonteOriginal?: string | null;
  fonteDescoberta?: string | null;
  nivelConfiabilidade?: string;
  dataUltimaChecada?: string | null;
  documentosFaltantes?: string[];
  checklist?: Array<{ tarefa: string; concluido: boolean; responsavel: string; prazo: string }>;
  protocolo?: string | null;
  resultado?: string | null;
}) {
  return request<{ item: Oportunidade }>("/oportunidades", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function listOportunidades() {
  return request<ListResponse<Oportunidade>>("/oportunidades");
}

export async function getOportunidade(id: string) {
  return request<{ item: Oportunidade }>(`/oportunidades/${id}`);
}

export async function patchOportunidade(id: string, payload: Partial<Oportunidade>) {
  return request<{ item: Oportunidade }>(`/oportunidades/${id}`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export async function listArtistas() {
  return request<ListResponse<Artista>>("/artistas");
}

export async function createArtista(payload: {
  nome: string;
  tipo?: string;
  area?: string;
  cidade?: string;
  projetos?: number;
  oportunidadesAtivas?: number;
  statusDocumental?: string;
  bio?: string;
  links?: string[];
  contatos?: string[];
  tags?: string[];
}) {
  return request<{ item: Artista }>("/artistas", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function getArtista(id: string) {
  return request<ArtistaDetailResponse>(`/artistas/${id}`);
}

export async function createProjeto(payload: {
  artistaId: string;
  nome: string;
  descricao?: string;
  status?: string;
  orcamento?: number;
  editaisRelacionados?: string[];
  tags?: string[];
}) {
  return request<{ item: Projeto }>("/projetos", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function listProjetos() {
  return request<ListResponse<Projeto>>("/projetos");
}

export async function createDocumento(payload: {
  nome: string;
  status?: string;
  responsavel?: string;
  arquivo?: string | null;
  ownerType: "artist" | "project" | "opportunity";
  ownerId: string;
  tipo?: string;
  validade?: string | null;
  oportunidadeId?: string | null;
  editalId?: string | null;
  versao?: string;
  textoExtraido?: string;
  resumoIa?: string;
  checklistGerado?: boolean;
  fonteDocumento?: string | null;
}) {
  return request<{ item: Documento }>("/documentos", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function listDocumentos() {
  return request<ListResponse<Documento>>("/documentos");
}

export async function listMatches() {
  return request<ListResponse<MatchOportunidadeProjeto>>("/matches");
}

export async function listSources() {
  return request<ListResponse<Source>>("/sources");
}

export async function createSource(payload: {
  name: string;
  type?: string;
  url: string;
  active?: boolean;
  frequencyMinutes?: number;
  notes?: string;
  esfera?: string;
  confiabilidade?: string;
  metodoCaptura?: string;
  precisaValidacaoHumana?: boolean;
  classificacao?: string;
}) {
  return request<{ item: Source }>("/sources", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function patchSource(
  id: string,
  payload: Partial<
    Pick<
      Source,
      | "name"
      | "type"
      | "url"
      | "active"
      | "frequencyMinutes"
      | "notes"
      | "esfera"
      | "confiabilidade"
      | "metodoCaptura"
      | "precisaValidacaoHumana"
      | "classificacao"
    >
  >,
) {
  return request<{ item: Source }>(`/sources/${id}`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export async function syncSource(id: string) {
  return request<{ source: Source; discoveredCount: number; createdCount: number; editais: Edital[] }>(`/sources/${id}/sync`, {
    method: "POST",
  });
}

export async function syncAllSources() {
  return request<{ items: Array<{ sourceId: string; ok: boolean; status: number; result?: unknown; error?: string }> }>("/sources/sync", {
    method: "POST",
  });
}

export async function listIngestions() {
  return request<ListResponse<Ingestion>>("/ingestions");
}

export async function getChatMessages(scope: "edital" | "oportunidade", id: string) {
  return request<ListResponse<ChatMessage>>(`/chat/${scope}/${id}/messages`);
}

export async function sendChatMessage(
  scope: "edital" | "oportunidade",
  id: string,
  content: string,
) {
  return request<ListResponse<ChatMessage>>(`/chat/${scope}/${id}/messages`, {
    method: "POST",
    body: JSON.stringify({ content }),
  });
}

export function formatMoney(value: number) {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
    maximumFractionDigits: 0,
  }).format(value);
}

export function normalizeLabel(value: string) {
  const map: Record<string, string> = {
    "Em revisao": "Em revisão",
    "Concluidos": "Concluídos",
    "Concluido": "Concluído",
    "Em analise": "Em análise",
    "Medio": "Médio",
    "Nao informado": "Não informado",
    "Musica": "Música",
    "Inovacao": "Inovação",
    "Artes Visuais": "Artes Visuais",
  };

  return map[value] || value;
}

export function riskBadgeClass(risk: string) {
  switch (normalizeLabel(risk)) {
    case "Alto":
      return "bg-red-100 text-red-700 border-red-200";
    case "Médio":
      return "bg-yellow-100 text-yellow-700 border-yellow-200";
    case "Baixo":
      return "bg-green-100 text-green-700 border-green-200";
    default:
      return "bg-slate-100 text-slate-700 border-slate-200";
  }
}
